/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_NativeMemoryUtils */

#ifndef _Included_com_example_demo_NativeMemoryUtils
#define _Included_com_example_demo_NativeMemoryUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_NativeMemoryUtils
 * Method:    allocateAndFillMemory
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_demo_NativeMemoryUtils_allocateAndFillMemory
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_example_demo_NativeMemoryUtils
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_demo_NativeMemoryUtils_freeMemory
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif 